import time
from selenium import webdriver
from selenium.webdriver.common.by import By

driver=webdriver.Chrome()
driver.maximize_window()
# # driver.get("https://www.google.co.in")
# url="https://www.flipkart.com/"
# driver.get(url)
# print("Title :",driver.title)
# print("Length of the title:",len(driver.title))
# print("Current URL : ",driver.current_url)
# print("current url and driver url is same or not :",driver.current_url.__contains__("https://www.flipkart.com/"))
# # print("Page source : ",driver.page_source)
# print("Page source length  : ",len(driver.page_source))
# time.sleep(5)
# driver.close()

# driver.get("https://www.google.co.in")
# time.sleep(3)
# driver.get("https://www.flipkart.com/")
# time.sleep(3)
# print("Ensureing the flipkart:",driver.current_url.__contains__("https://www.flipkart.com"))
# driver.back()
# time.sleep(3)
# print("Ensureing the google:",driver.current_url.__contains__("https://www.google.co.in"))
# driver.forward()

driver.get("https://www.toolsqa.com/selenium-training/")
register = driver.find_element(By.XPATH,value="//div[@class='selenium-training-page']/div[1]/div/div[1]/div[2]/a")
print(register.size)
print(register.value_of_css_property("color"))
print(register.location)
driver.save_screenshot("homepage.png")
register.click()

print(driver.current_url)
time.sleep(3)
driver.back()
print(driver.current_url)
time.sleep(3)
driver.forward()
print(driver.current_url)
time.sleep(3)
driver.back()
time.sleep(3)
driver.refresh()
time.sleep(3)
driver.close()